---
title: "Sung Rye Park"
subtitle: "Bioinformatics Scientist"
author: ""
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

## Professional summary  

Current position at  **Dana Farber Cancer Institute**  
<br>
Senior Bioinformatics Scientist with over 6 years of hands-on experience in various NGS data analysis and a strong publication record, including a co-first authorship in Nature Immunology (2024) for CD8+ Memory T cell fate. Proficient in the integration of comprehensive multi-omic datasets, encompassing transcriptomic, genomic, epigenomic, and clinical data, to drive research and development in immuno-oncology. At Dana Farber Cancer Institute, played a pivotal role in analyzing complex drug combination testing datasets and provided critical bioinformatics consultation. Passionate about applying a blend of technical proficiency and biological insights to enhance team success, particularly within innovative personalized cancer therapy programs.    

<br>

## Resume (pdf) <a id="resume-pdf"></a>   
<a href="info/resume/SungRyePark_resume2405.pdf" style="font-size: 20px;">Sung Rye Park's resume</a><br>


## Work Sample pages<a id="samples"></a>     

<a href="samplePages/scRNAseq.html" style="font-size: 24px;">single cell RNA-seq</a><br>
<a href="samplePages/RNAseq.html" style="font-size: 24px;">bulk RNA-seq</a><br>
<a href="samplePages/ChIP_seq.html" style="font-size: 24px;">ChIP-seq (applicable to ATAC-seq, Cut&Run)</a><br>
<a href="samplePages/TCR_seq.html" style="font-size: 24px;">TCR-seq</a><br>


<br>
<a href="etc/Data_Processing.html" style="font-size: 24px;">Data_Processing in Linux env</a><br>
<a href="samplePages/Simple_RShiny_app_gene_gene_scatterplot.html" style="font-size: 24px;">Simple_shiny_app</a><br>

<br>
<a href="etc/Basic_github.html" style="font-size: 24px;">Basic Github usage</a><br>

<br>


<span style="font-size: 20px;">Cell type annotation database processing(will be updated)</span><br> 
<span style="font-size: 20px;">Plot gallery (will be updated) </span><br>  
<span style="font-size: 20px;">WES (will be updated)</span><br>
<br>
<br><br>


### Github  <a id="github"></a>     
https://github.com/Sung2021 

### LinkedIn Profile  <a id="linkedin"></a>   

<a href="https://www.linkedin.com/in/sung-rye-park-8a130098/" style="font-size: 18px;">Work History in LinkedIn</a><br>
<br><br>


## First/co-first authorship publications (pdf)  <a id="first_author"></a>  

<a href="info/papers/NI_Sung_s41590-023-01720-w_reduced_size2.pdf" style="font-size: 14px;">The transcriptional cofactor Tle3 reciprocally controls effector and central memory CD8+ T cell fates. (Nature Immunology, 2024)</a><br>

<a href="info/papers/CellReports.2020.Sung_reduced_size2.pdf" style="font-size: 14px;">Single cell transcriptome analysis of colon cancer cell response to 5-fluorouracil-induced DNA damage (Cell Reports, 2020)</a><br>

<a href="info/papers/American_Journal_of_Physiology.2020.Sung_reduced_size.pdf" style="font-size: 14px;">Holistic Characterization of Single Hepatocyte Transcriptome Responses to High Fat Diet (American Journal of Physiology-Endocrionlogy and Metabolism, 2020)</a><br>



<br>

## Skills  <a id="skills"></a>  
* Proficient in a wide array of NGS data pipelines and bioinformatics analyses including scRNA-seq, TCR-seq, CITE-Seq, ATAC-seq, bulk RNA-seq, as well as integrative approaches with TCGA and CCLE for genomic and epigenomic studies 
* Proficient in Linux, with programming skills in Python and R, and skilled use of bioinformatics tools including Cellranger, Salmon, and a suite of sequence alignment and analysis utilities 
* Well-versed in peak calling, genomic visualization, and analysis using open- source platforms such as Seurat, scanpy, and the USCC Genome Browser
* Expertise in pathway and network analysis to elucidate complex biological pathways, and statistical analysis for robust genomic data interpretation
* Familiarity with high-performance computing environments and adept at managing in-lab NGS pipelines, ensuring quality and reproducibility 
* Skilled in data visualization and presentation, utilizing tools like ggplot2, Shiny, and Rmarkdown, to effectively communicate complex data to diverse audiences 
* Expertise in immunology, oncology, and molecular biology with practical experience in public dataset analysis 
* Developed and maintained specialized assay platforms including Drop-seq, Seq-well, and Seq-scope
* Proficient in NGS library generation, particularly with single cell 10X genomics and RNA-seq
* Autonomous work style, efficiently conducting research with minimal oversight
Guiding and mentoring interns in bioinformatics practices and project work
* Consulting with collaborators to identify and apply novel bioinformatics analysis methods
* Managing documentation and workflow sharing across collaborative platforms
* Keeping meticulous records of both raw and processed data storage

<br>

## Experience  <a id="experience"></a>
* Senior Bioinformatics scientist at Dana Farber Cancer Institute 2022-  

  - DGK inhibitor efficacy testing in combination with Nivolumab for SCLC     
  - DS-1062 and Pembrolizumab testing for SCLC   
  - EZH2 inhibitor candidates searching using ChIP-seq   
  - Evaluation of STING agonist (ADU-100) effects in mouse PBMCs and the tumor immune environment   
  - TAK-676 and PD-1 blockade in SCLC   
  - Immune cell trafficking within in-house device culture   
  - Integrative analysis ofanti-CD47 therapy efficacy in PTCL-resistant mouse models   
  - Supporting manuscript writings.  
  - (more)
<br><br>

* Postdoctoral Fellow at Hackensack Meridian Health 
* Postdoctoral Fellow at University of Michigan

## Publications  <a id="publications"></a> 
* The transcriptional cofactor Tle3 reciprocally controls effector and central memory CD8+ T cell fates. (Nature Immunology, 2024. X.Zhao, W.Hu, S.R.Park, S.Zhu, S.S.Hu, C.Zang, W.Peng, Q.Shan ,H.H. Xue. **co-first** (Zhao, W.Hu, Park and Zhu as co-first authors with equal contribution) (https://doi.org/10.1038/s41590-023-01720-w)
* SiftCell: A robust framework to detect and isolate cell-containing droplets from single-cell RNA sequence reads. (Cell Systems, 2023) Jingyue Xi, Sung Rye Park, Jun Hee Lee and Hyun Min Kang. (https://doi.org/10.1016/j.cels.2023.06.002)
* Sublethal whole-body irradiation induces permanent loss and dysfunction in pathgen-specific circulating memory CD8T cell populations. (PNAS, July 2023) Mohammad Heidarian, Iassac J Jensen, Shravan Kumar Kannan, Lecia L Pewe, Mariah Hassert, Sung Rye Park, Hai-Hui Xue, John Harty, Vladimir Badovinac. (https://doi.org/10.1073/pnas.2302785120.)
* Simultaneous loss of TSC1 and DEPDC5 in skeletal and cardiac muscles produces early-onset myopathy and cardiac dysfunction associated with oxidative damage and SQSTM1/p62 accumulation. (Autophagy, 2021) Chun-Seok Cho, Yongsung Kim, Sung-Rye Park, Boyoung Kim, Carol Davis, Irene Hwang, Susan V Brooks, Jun Hee Lee, Myungjin Kim. (https://doi.org/10.1080/15548627.2021.2016255)
* Seq-Scope: Microscopic examination of spatial transcriptome using Seq-Scope. (Cell, 2021) Chun-Seok Cho, Jingyue Xi, Yichen Si, Sung-Rye Park, Jer-En Hsu, Myungjin Kim, Goo Jun, Hyun-Min Kang, Jun Hee Lee. (https://doi.org/10.1016/j.cell.2021.05.010)
* Single cell transcriptome analysis of colon cancer cell response to 5-fluorouracil-induced DNA damage (Cell Reports, 2020) Sung Rye Park, Sim Namkoong, Zac Zezhi Zhang, Leon Friesen, Euisik Yoon, Chang H. Kim, Hojoong Kwak, Hyun Min Kang and Jun Hee Lee. (https://doi.org/10.1016/j.celrep.2020.108077)  **first**
* Holistic Characterization of Single Hepatocyte Transcriptome Responses to High Fat Diet (American Journal of Physiology-Endocrionlogy and Metabolism, 2020) Sung Rye Park, Chun-Seok Cho, Hyun Min Kang and Jun Hee Lee. (https://doi.org/10.1152/ajpendo.00391.2020)  **first**
* Concurrent activation of growth factor and nutrient arms of mTORC1 induces oxidative liver injury. Cell Discovery volume 5, Article number: 60 (2019) Chun-Seok Cho, Allison Ho, Sim Namkoong, Sung-Rye Park, Shuangcheng Wu, Boyoung Kim, Amanda James, Bondong Gu, Ian A. Semple, Mohamed A. Tohamy, Sumeet Solanki, Uhn-Soo Cho, Joel K. Greenson, Yatrik Shah, Myungjin Kim, Jun Hee Lee. (https://doi.org/10.1152/ajpendo.00391.2020)



## Education  <a id="education"></a>
* Ph.D. Plant Biology, University of Texas at Austin 2017
* MA. Biology Seoul National University 2010   

<br><br>

Last update: `r format(Sys.Date())`

<br><br>